INSERT OR IGNORE INTO system_settings(key, value) VALUES
  ('initial_admin_points', '1000000'),
  ('initial_user_points', '1000'),
  ('pricing_unit_tokens', '1000'),
  ('settlement_round_digits', '4'),
  ('fallback_input_price_per_unit', '1.0'),
  ('fallback_output_price_per_unit', '3.0'),
  ('fallback_cache_price_per_unit', '0.2'),
  ('surge_idle_multiplier', '0.5'),
  ('surge_normal_multiplier', '1.0'),
  ('surge_peak_multiplier', '1.5'),
  ('routing_max_attempts', '8'),
  ('routing_retry_cooldown_seconds', '30'),
  ('routing_fire_sale_weight_multiplier', '5.0'),
  ('ledger_queue_capacity', '4096'),
  ('affinity_cache_capacity', '4096'),
  ('default_api_key_spend_limit_points', '1000'),
  ('default_channel_name', 'OpenAI Pool'),
  ('default_channel_provider', 'openai'),
  ('default_channel_base_url', 'https://api.openai.com'),
  ('default_channel_models', 'gpt-*,gpt-4o*'),
  ('default_channel_windows_json', '[{"name":"Monthly","limit_tokens":1000000,"period_unit":"month","period_count":1,"timezone":"UTC"},{"name":"Daily","limit_tokens":200000,"period_unit":"day","period_count":1,"timezone":"UTC"},{"name":"Hourly","limit_tokens":50000,"period_unit":"hour","period_count":1,"timezone":"UTC"}]'),
  ('default_channel_fire_sale_days_before', '3'),
  ('default_channel_fire_sale_remaining_pct', '0.25'),
  ('default_channel_fire_sale_discount', '0.2'),
  ('default_channel_provider_share', '0.7');
